import type { Metadata } from "next";
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import { ToastContainer } from "react-toastify";

// import localFont from "next/font/local";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// className={${geistSans.variable} ${geistMono.variable}}

export const metadata: Metadata = {
  title: "Join Looms",
  description: "Generated by create next app",
  icons: {
    icon: "/Ellipse6.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastContainer position="top-right"/>
        {children}
      </body>
    </html>
  );
}
